AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PaymentVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: excel-ai-payment-verification
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      Environment:
        Variables:
          RAZORPAY_KEY_SECRET: !Ref RazorpayKeySecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentTable
      Events:
        PaymentApi:
          Type: Api
          Properties:
            Path: /payment
            Method: post
        PaymentApiOptions:
          Type: Api
          Properties:
            Path: /payment
            Method: options

  PaymentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: excel-ai-payments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userEmail
          AttributeType: S
      KeySchema:
        - AttributeName: userEmail
          KeyType: HASH

Parameters:
  RazorpayKeySecret:
    Type: String
    Description: Razorpay Key Secret
    NoEcho: true

Outputs:
  PaymentApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/payment"