AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RazorpayKeyId:
    Type: String
    Description: Razorpay Key ID
    Default: rzp_test_GwLaqT264JyMlU
  RazorpayKeySecret:
    Type: String
    NoEcho: true
    Description: Razorpay Key Secret

Resources:
  # DynamoDB Table for Orders
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: advexcel-orders
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Functions
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/
      Handler: create-order.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          RAZORPAY_KEY_ID: !Ref RazorpayKeyId
          RAZORPAY_KEY_SECRET: !Ref RazorpayKeySecret
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /create-order
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"

  VerifyPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda/
      Handler: verify-payment.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          RAZORPAY_KEY_SECRET: !Ref RazorpayKeySecret
          ORDERS_TABLE: !Ref OrdersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        VerifyPayment:
          Type: Api
          Properties:
            Path: /verify-payment
            Method: post
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"

Outputs:
  ApiGatewayEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"